# Generated by Django 4.2.24 on 2025-09-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('jugador1', models.CharField(max_length=100)),
                ('jugador2', models.CharField(max_length=100)),
                ('jugador3', models.CharField(max_length=100)),
                ('jugador4', models.CharField(max_length=100)),
                ('jugador5', models.CharField(max_length=100)),
                ('racha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_Iniciadores', models.IntegerField()),
                ('numero_Controlador', models.IntegerField()),
                ('numero_Centinela', models.IntegerField()),
                ('numero_Duelista', models.IntegerField()),
                ('imagen_mapa', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('counter1', models.CharField(max_length=100)),
                ('counter2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('puntuacion', models.FloatField()),
                ('Kills_per_Round', models.FloatField()),
                ('Deaths_per_Round', models.FloatField()),
                ('Opening_Kills_per_Round', models.FloatField()),
                ('Headshot_per_Round', models.FloatField()),
                ('Kill_Cost', models.FloatField()),
                ('Mejor_Mapa', models.CharField(max_length=100)),
                ('Peor_Mapa', models.CharField(max_length=100)),
                ('Rol_Recomendado', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg.equipo')),
            ],
        ),
    ]
