# Generated by Django 4.2.24 on 2025-09-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='imagen_personaje',
            field=models.URLField(default=None),
        ),
    ]
