# Generated by Django 4.2.24 on 2025-09-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0002_personaje_imagen_personaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen_equipo',
            field=models.URLField(default=None),
        ),
    ]
