# Generated by Django 4.2.24 on 2025-09-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0003_equipo_imagen_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen_equipo',
            field=models.ImageField(default=None, max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='imagen_mapa',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='imagen_personaje',
            field=models.ImageField(default=None, max_length=200, upload_to=''),
        ),
    ]
